// Amber web viewer ESLint config (flat). Issue #207 batch 1.
// Scope: the TypeScript/React toolchain under src/, server/, tests/, and the
// config files at the app root. Generated files are ignored (routeTree.gen.ts
// carries its own /* eslint-disable */ and is regenerated by the router
// plugin). The root repo's eslint.config.mjs ignores apps/web/ — the two
// toolchains lint independently.
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist/',
      'node_modules/',
      'src/routeTree.gen.ts',
      'playwright-report/',
      'test-results/',
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': 'warn',
      // Deferred findings (issue #207 batch 1 is tooling-only): 5 real
      // set-state-in-effect sites (theme/settings hydration, SSE state)
      // need behavior-adjacent refactors; keep them visible, not blocking.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
  {
    files: ['server/**/*.{ts,mts}', 'tests/**/*.{ts,tsx}', '*.config.{ts,mts,js}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.node,
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
      },
    },
  },
  {
    // Route files export Route/loaders/components side by side by TanStack
    // Router convention — fast-refresh export purity does not apply there.
    files: ['src/routes/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // Mocks and fixtures intentionally use loose types.
    files: ['tests/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
);
