"use strict";

const { inspectPageHealth } = require("./context-page-health");

function renderContextIndex(targetRoot, pages) {
	const lines = [
		"# Context Pages",
		"",
		"Machine-maintained index of `amber context` pages. Do not edit by hand;",
		"regenerated by `amber context ingest` / `refresh` / `delete`.",
		"",
	];
	if (pages.length === 0) {
		lines.push("No context pages.");
	} else {
		lines.push("| pageId | title | blocks | sources | status |");
		lines.push("| --- | --- | --- | --- | --- |");
		for (const page of pages) {
			const blocks = Array.isArray(page.blocks) ? page.blocks.length : 0;
			const sources = page.sources ? Object.keys(page.sources).length : 0;
			const status = inspectPageHealth(targetRoot, page).status;
			const title = (page.title || "").replace(/\|/g, "\\|");
			lines.push(`| ${page.pageId} | ${title} | ${blocks} | ${sources} | ${status} |`);
		}
	}
	return `${lines.join("\n")}\n`;
}

function validateContextIndex(pages, output) {
	if (!output.endsWith("\n")) return { ok: false, detail: "projection output lacks final newline" };
	const lines = output.slice(0, -1).split("\n");
	if (pages.length === 0) {
		const expected = [
			"# Context Pages",
			"",
			"Machine-maintained index of `amber context` pages. Do not edit by hand;",
			"regenerated by `amber context ingest` / `refresh` / `delete`.",
			"",
			"No context pages.",
		];
		return lines.join("\n") === expected.join("\n")
			? { ok: true }
			: { ok: false, detail: "empty projection output is incomplete" };
	}
	const headers = [
		"# Context Pages",
		"",
		"Machine-maintained index of `amber context` pages. Do not edit by hand;",
		"regenerated by `amber context ingest` / `refresh` / `delete`.",
		"",
		"| pageId | title | blocks | sources | status |",
		"| --- | --- | --- | --- | --- |",
	];
	if (lines.length !== headers.length + pages.length) {
		return { ok: false, detail: "projection row count does not match authoritative Context Pages" };
	}
	if (!headers.every((header, index) => lines[index] === header)) {
		return { ok: false, detail: "projection headers do not match the Context index contract" };
	}
	for (const [index, page] of pages.entries()) {
		const blocks = Array.isArray(page.blocks) ? page.blocks.length : 0;
		const sources = page.sources ? Object.keys(page.sources).length : 0;
		const title = (page.title || "").replace(/\|/g, "\\|");
		const prefix = `| ${page.pageId} | ${title} | ${blocks} | ${sources} | `;
		const row = lines[headers.length + index];
		if (!row.startsWith(prefix) || !/^[a-z][a-z-]* \|$/.test(row.slice(prefix.length))) {
			return { ok: false, detail: `projection row for ${page.pageId} is incomplete` };
		}
	}
	return { ok: true };
}

module.exports = { renderContextIndex, validateContextIndex };
