"use strict";

// File layout for the amber context layer (ADR-0009 D3).
//
//   .amber/context/pages/<pageId>.json    accepted pages (dir scan = manifest)
//   .amber/context/requests/<id>.json     distillation contracts (requests)
//   .amber/context/events.jsonl           append-only operational events (D9)
//   docs/wiki/context-index.md            the one generated wiki file (D3)

const fs = require("node:fs");
const path = require("node:path");
const { readJson, resolvePathWithin } = require("./fs-utils");
const { inspectPageHealth } = require("./context-page-health");

const SCHEMA_VERSION = "1.0.0";
const INDEX_REL = path.join("docs", "wiki", "context-index.md");
const PAGE_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function pagesDir(targetRoot) {
	return resolvePathWithin(targetRoot, path.join(".amber", "context", "pages"), {
		label: "Context Pages directory",
	});
}

function requestsDir(targetRoot) {
	return resolvePathWithin(targetRoot, path.join(".amber", "context", "requests"), {
		label: "Context requests directory",
	});
}

function eventsPath(targetRoot) {
	return resolvePathWithin(targetRoot, path.join(".amber", "context", "events.jsonl"), {
		label: "Context events file",
	});
}

function indexPath(targetRoot) {
	return resolvePathWithin(targetRoot, INDEX_REL, { label: "Context index file" });
}

function pagePath(targetRoot, pageId) {
	if (typeof pageId !== "string" || !PAGE_ID_RE.test(pageId)) {
		throw new Error(`Invalid Context Page id: ${pageId}. Expected kebab-case.`);
	}
	pagesDir(targetRoot);
	return resolvePathWithin(targetRoot, path.join(".amber", "context", "pages", `${pageId}.json`), {
		label: "Context Page file",
	});
}

/** List accepted pages as [{ pageId, filePath }] via directory scan. */
function listPages(targetRoot) {
	const dir = pagesDir(targetRoot);
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir, { withFileTypes: true })
		.filter((d) => d.isFile() && d.name.endsWith(".json"))
		.map((d) => ({ pageId: d.name.replace(/\.json$/, ""), filePath: path.join(dir, d.name) }))
		.sort((a, b) => a.pageId.localeCompare(b.pageId));
}

/** Read a page object, or null when missing. Malformed persisted pages are errors. */
function readPage(targetRoot, pageId) {
	const file = pagePath(targetRoot, pageId);
	if (!fs.existsSync(file)) return null;
	return readJson(file);
}

function ensureDir(dir) {
	fs.mkdirSync(dir, { recursive: true });
}

/** Persist a page, synchronize the generated index, and emit a page-write event. */
function writePage(targetRoot, page, event = {}) {
	const dir = pagesDir(targetRoot);
	ensureDir(dir);
	const file = pagePath(targetRoot, page.pageId);
	fs.writeFileSync(file, JSON.stringify(page, null, 2) + "\n", "utf8");
	regenerateIndex(targetRoot);
	appendEvent(targetRoot, {
		kind: "page-written",
		pageId: page.pageId,
		...event,
	});
	return file;
}

/** Remove a page file, returning true when it existed. */
function deletePage(targetRoot, pageId) {
	const file = pagePath(targetRoot, pageId);
	if (!fs.existsSync(file)) return false;
	fs.rmSync(file, { force: true });
	regenerateIndex(targetRoot);
	appendEvent(targetRoot, { kind: "page-deleted", pageId });
	return true;
}

/**
 * Regenerate docs/wiki/context-index.md from the directory scan.
 * Status is derived at the store boundary via page health so write/delete
 * never need a second caller-supplied statusMap pass.
 * @param {string} targetRoot
 * @param {Record<string,string>} [statusMap] optional pageId -> status override
 */
function regenerateIndex(targetRoot, statusMap) {
	const pages = listPages(targetRoot);
	const file = indexPath(targetRoot);
	ensureDir(path.dirname(file));
	const lines = [];
	lines.push("# Context Pages");
	lines.push("");
	lines.push("Machine-maintained index of `amber context` pages. Do not edit by hand;");
	lines.push("regenerated by `amber context ingest` / `refresh` / `delete`.");
	lines.push("");
	if (pages.length === 0) {
		lines.push("No context pages.");
	} else {
		lines.push("| pageId | title | blocks | sources | status |");
		lines.push("| --- | --- | --- | --- | --- |");
		for (const { pageId } of pages) {
			const page = readPage(targetRoot, pageId);
			if (!page) continue;
			const blocks = Array.isArray(page.blocks) ? page.blocks.length : 0;
			const sources = page.sources ? Object.keys(page.sources).length : 0;
			const status =
				statusMap && Object.prototype.hasOwnProperty.call(statusMap, pageId)
					? statusMap[pageId]
					: inspectPageHealth(targetRoot, page).status;
			const title = (page.title || "").replace(/\|/g, "\\|");
			lines.push(`| ${pageId} | ${title} | ${blocks} | ${sources} | ${status} |`);
		}
	}
	fs.writeFileSync(file, lines.join("\n") + "\n", "utf8");
	return file;
}

/** Append one JSON line to the append-only event log. */
function appendEvent(targetRoot, event) {
	const file = eventsPath(targetRoot);
	ensureDir(path.dirname(file));
	fs.appendFileSync(
		file,
		JSON.stringify({ ...event, at: new Date().toISOString() }) + "\n",
		"utf8",
	);
}

/** Read all events as objects. */
function readEvents(targetRoot) {
	const file = eventsPath(targetRoot);
	if (!fs.existsSync(file)) return [];
	return fs
		.readFileSync(file, "utf8")
		.split("\n")
		.filter(Boolean)
		.map((line) => {
			try {
				return JSON.parse(line);
			} catch {
				return null;
			}
		})
		.filter(Boolean);
}

module.exports = {
	SCHEMA_VERSION,
	INDEX_REL,
	pagesDir,
	requestsDir,
	eventsPath,
	indexPath,
	pagePath,
	listPages,
	readPage,
	writePage,
	deletePage,
	regenerateIndex,
	appendEvent,
	readEvents,
};
