import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsible: false,
      items: [
        'start-here/index',
        'start-here/installation',
        'start-here/first-governed-workflow',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      items: [
        'concepts/index',
        'concepts/target-repository',
        'concepts/amber-setup',
        'concepts/session',
        'concepts/route',
        'concepts/wiki',
        'concepts/evidence',
        'concepts/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      items: [
        'guides/index',
        'guides/adopting-existing-project',
        'guides/session-handoff-and-continuity',
        'guides/governance-gates-and-audit',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      items: [
        'reference/index',
        {
          type: 'category',
          label: 'CLI Commands',
          items: [
          "reference/cli/index",
          "reference/cli/audit",
          "reference/cli/init",
          "reference/cli/doctor",
          "reference/cli/next",
          "reference/cli/plan",
          "reference/cli/handoff",
          "reference/cli/session",
          "reference/cli/wiki",
          "reference/cli/gate",
          "reference/cli/policy",
          "reference/cli/adapter",
          "reference/cli/runner",
          "reference/cli/release",
          "reference/cli/maintain",
          "reference/cli/retention",
          "reference/cli/external",
          "reference/cli/breakglass",
          "reference/cli/review",
          "reference/cli/accept",
          "reference/cli/learnings",
          "reference/cli/break-loop",
          "reference/cli/pack",
          "reference/cli/profile",
          "reference/cli/task",
          "reference/cli/result",
          "reference/cli/agent",
          "reference/cli/team",
          "reference/cli/maintenance",
          "reference/cli/adoption",
          "reference/cli/loop",
          "reference/cli/ledger",
          "reference/cli/route",
          "reference/cli/status",
          "reference/cli/drift",
          "reference/cli/sync",
          "reference/cli/migrate",
          "reference/cli/governance",
          "reference/cli/execution",
          "reference/cli/security",
          "reference/cli/feature",
          "reference/cli/clean",
          "reference/cli/explain",
          "reference/cli/hooks",
          "reference/cli/workflow",
          "reference/cli/context",
          "reference/cli/memory",
          "reference/cli/projection",
          "reference/cli/knowledge",
          "reference/cli/phase",
          "reference/cli/artifact",
          "reference/cli/principal",
          "reference/cli/eval",
          "reference/cli/evidence",
          "reference/cli/approval",
          "reference/cli/contracts"
],
        },
        'reference/schemas',
        'reference/action-types',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsible: false,
      items: [
        'troubleshooting/index',
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsible: true,
      items: [
        'about/index',
        'about/version-history',
        'about/boundaries',
        'about/contributing',
      ],
    },
  ],
};

export default sidebars;
