/**
 * On-demand persistence for transcript digests (Session Lens A0 / decision #3:
 * default ephemeral, save only when explicitly requested).
 *
 * Saved digests live under `.amber/lens/`, which is git-ignored by a
 * `.gitignore` this module writes before any digest — so a saved digest can
 * never be committed by accident. The digest itself is already redacted by the
 * transcript reader; we assert that invariant with leak tests.
 */

import fs from 'fs';
import path from 'path';
import { readRepoTranscript, type TranscriptDetail } from './claude-transcript-reader';
import { AMBER_STATE_DIR } from './state-dir';

export interface LensSaveOptions {
  repoPath: string;
  repoRoot: string;
  claudeHome?: string;
}

export interface LensSaveResult {
  id: string;
  path: string;
  turnCount: number;
}

function ensureLensDir(repoRoot: string): string {
  const lensDir = path.join(repoRoot, AMBER_STATE_DIR, 'lens');
  fs.mkdirSync(lensDir, { recursive: true });
  // Defense in depth: ignore everything in this directory so a redacted
  // digest still cannot be committed.
  const gitignorePath = path.join(lensDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, '# Amber Session Lens digests — never commit.\n*\n');
  }
  return lensDir;
}

function digestMarkdown(detail: TranscriptDetail): string {
  const lines: string[] = [];
  lines.push(`# Session digest: ${detail.id}`);
  lines.push('');
  lines.push(`- Turns: ${detail.turnCount}`);
  if (detail.gitBranch) {
    lines.push(`- Branch: ${detail.gitBranch}`);
  }
  if (detail.firstTimestamp) {
    lines.push(`- First: ${detail.firstTimestamp}`);
  }
  if (detail.lastTimestamp) {
    lines.push(`- Last: ${detail.lastTimestamp}`);
  }
  const tools = [...new Set(detail.turns.flatMap((t) => t.tools))];
  if (tools.length > 0) {
    lines.push(`- Tools used: ${tools.join(', ')}`);
  }
  lines.push('');
  lines.push('> Secrets redacted. Generated by Amber Session Lens (ephemeral by default).');
  lines.push('');
  for (const turn of detail.turns) {
    const toolSuffix = turn.tools.length ? ` [${turn.tools.join(', ')}]` : '';
    lines.push(`## ${turn.type}${toolSuffix}`);
    if (turn.text) {
      lines.push('');
      lines.push(turn.text);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function saveTranscriptDigest(id: string, opts: LensSaveOptions): LensSaveResult | null {
  // redact defaults to true in the reader; never disabled here.
  const detail = readRepoTranscript(opts.repoPath, id, { claudeHome: opts.claudeHome });
  if (!detail) {
    return null;
  }

  const lensDir = ensureLensDir(opts.repoRoot);
  const filePath = path.join(lensDir, `${id}.digest.md`);
  fs.writeFileSync(filePath, digestMarkdown(detail));

  return { id, path: filePath, turnCount: detail.turnCount };
}
