/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as RoutesRouteRouteImport } from './routes/routes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranscriptsIndexRouteImport } from './routes/transcripts/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as TranscriptsIdRouteImport } from './routes/transcripts/$id'
import { Route as SessionsIdRouteRouteImport } from './routes/sessions/$id/route'
import { Route as RoutesIdRouteRouteImport } from './routes/routes/$id/route'
import { Route as SessionsIdIndexRouteImport } from './routes/sessions/$id/index'
import { Route as RoutesIdIndexRouteImport } from './routes/routes/$id/index'
import { Route as SessionsIdTimelineRouteImport } from './routes/sessions/$id/timeline'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteRoute = RoutesRouteRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsIndexRoute = TranscriptsIndexRouteImport.update({
  id: '/transcripts/',
  path: '/transcripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesRouteRoute,
} as any)
const TranscriptsIdRoute = TranscriptsIdRouteImport.update({
  id: '/transcripts/$id',
  path: '/transcripts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRouteRoute = SessionsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const RoutesIdRouteRoute = RoutesIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoutesRouteRoute,
} as any)
const SessionsIdIndexRoute = SessionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsIdRouteRoute,
} as any)
const RoutesIdIndexRoute = RoutesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesIdRouteRoute,
} as any)
const SessionsIdTimelineRoute = SessionsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SessionsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routes': typeof RoutesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/gates': typeof GatesRoute
  '/settings': typeof SettingsRoute
  '/routes/$id': typeof RoutesIdRouteRouteWithChildren
  '/sessions/$id': typeof SessionsIdRouteRouteWithChildren
  '/transcripts/$id': typeof TranscriptsIdRoute
  '/routes/': typeof RoutesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/transcripts/': typeof TranscriptsIndexRoute
  '/sessions/$id/timeline': typeof SessionsIdTimelineRoute
  '/routes/$id/': typeof RoutesIdIndexRoute
  '/sessions/$id/': typeof SessionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gates': typeof GatesRoute
  '/settings': typeof SettingsRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
  '/routes': typeof RoutesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/transcripts': typeof TranscriptsIndexRoute
  '/sessions/$id/timeline': typeof SessionsIdTimelineRoute
  '/routes/$id': typeof RoutesIdIndexRoute
  '/sessions/$id': typeof SessionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routes': typeof RoutesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/gates': typeof GatesRoute
  '/settings': typeof SettingsRoute
  '/routes/$id': typeof RoutesIdRouteRouteWithChildren
  '/sessions/$id': typeof SessionsIdRouteRouteWithChildren
  '/transcripts/$id': typeof TranscriptsIdRoute
  '/routes/': typeof RoutesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/transcripts/': typeof TranscriptsIndexRoute
  '/sessions/$id/timeline': typeof SessionsIdTimelineRoute
  '/routes/$id/': typeof RoutesIdIndexRoute
  '/sessions/$id/': typeof SessionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/routes'
    | '/sessions'
    | '/gates'
    | '/settings'
    | '/routes/$id'
    | '/sessions/$id'
    | '/transcripts/$id'
    | '/routes/'
    | '/sessions/'
    | '/transcripts/'
    | '/sessions/$id/timeline'
    | '/routes/$id/'
    | '/sessions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gates'
    | '/settings'
    | '/transcripts/$id'
    | '/routes'
    | '/sessions'
    | '/transcripts'
    | '/sessions/$id/timeline'
    | '/routes/$id'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/routes'
    | '/sessions'
    | '/gates'
    | '/settings'
    | '/routes/$id'
    | '/sessions/$id'
    | '/transcripts/$id'
    | '/routes/'
    | '/sessions/'
    | '/transcripts/'
    | '/sessions/$id/timeline'
    | '/routes/$id/'
    | '/sessions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoutesRouteRoute: typeof RoutesRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  GatesRoute: typeof GatesRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptsIdRoute: typeof TranscriptsIdRoute
  TranscriptsIndexRoute: typeof TranscriptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/': {
      id: '/transcripts/'
      path: '/transcripts'
      fullPath: '/transcripts/'
      preLoaderRoute: typeof TranscriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/routes/': {
      id: '/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof RoutesRouteRoute
    }
    '/transcripts/$id': {
      id: '/transcripts/$id'
      path: '/transcripts/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof TranscriptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteRouteImport
      parentRoute: typeof RoutesRouteRoute
    }
    '/sessions/$id/': {
      id: '/sessions/$id/'
      path: '/'
      fullPath: '/sessions/$id/'
      preLoaderRoute: typeof SessionsIdIndexRouteImport
      parentRoute: typeof SessionsIdRouteRoute
    }
    '/routes/$id/': {
      id: '/routes/$id/'
      path: '/'
      fullPath: '/routes/$id/'
      preLoaderRoute: typeof RoutesIdIndexRouteImport
      parentRoute: typeof RoutesIdRouteRoute
    }
    '/sessions/$id/timeline': {
      id: '/sessions/$id/timeline'
      path: '/timeline'
      fullPath: '/sessions/$id/timeline'
      preLoaderRoute: typeof SessionsIdTimelineRouteImport
      parentRoute: typeof SessionsIdRouteRoute
    }
  }
}

interface RoutesIdRouteRouteChildren {
  RoutesIdIndexRoute: typeof RoutesIdIndexRoute
}

const RoutesIdRouteRouteChildren: RoutesIdRouteRouteChildren = {
  RoutesIdIndexRoute: RoutesIdIndexRoute,
}

const RoutesIdRouteRouteWithChildren = RoutesIdRouteRoute._addFileChildren(
  RoutesIdRouteRouteChildren,
)

interface RoutesRouteRouteChildren {
  RoutesIdRouteRoute: typeof RoutesIdRouteRouteWithChildren
  RoutesIndexRoute: typeof RoutesIndexRoute
}

const RoutesRouteRouteChildren: RoutesRouteRouteChildren = {
  RoutesIdRouteRoute: RoutesIdRouteRouteWithChildren,
  RoutesIndexRoute: RoutesIndexRoute,
}

const RoutesRouteRouteWithChildren = RoutesRouteRoute._addFileChildren(
  RoutesRouteRouteChildren,
)

interface SessionsIdRouteRouteChildren {
  SessionsIdTimelineRoute: typeof SessionsIdTimelineRoute
  SessionsIdIndexRoute: typeof SessionsIdIndexRoute
}

const SessionsIdRouteRouteChildren: SessionsIdRouteRouteChildren = {
  SessionsIdTimelineRoute: SessionsIdTimelineRoute,
  SessionsIdIndexRoute: SessionsIdIndexRoute,
}

const SessionsIdRouteRouteWithChildren = SessionsIdRouteRoute._addFileChildren(
  SessionsIdRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIdRouteRoute: typeof SessionsIdRouteRouteWithChildren
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIdRouteRoute: SessionsIdRouteRouteWithChildren,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoutesRouteRoute: RoutesRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  GatesRoute: GatesRoute,
  SettingsRoute: SettingsRoute,
  TranscriptsIdRoute: TranscriptsIdRoute,
  TranscriptsIndexRoute: TranscriptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
