blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Bandersnatch0x/amber-protocol/blob/master/README.md
    about: Check the documentation for usage guides and examples
  - name: Discussions
    url: https://github.com/Bandersnatch0x/amber-protocol/discussions
    about: Ask questions and discuss ideas with the community
