"use strict";

// Per-command help text shown by `amber <command> --help`.
// Single-line summaries are plain strings; multi-line summaries are arrays
// joined with newlines. Adding a command's help is a one-line data edit here,
// not a new branch in the CLI dispatcher.
const COMMAND_HELP = {
	init: "Create missing Amber starter files without overwriting existing files. Supports --dry-run.",
	audit: "Inspect an existing project without writing files. Supports --summary for bounded text output.",
	wiki: "Create missing Wiki starter files, skip existing files, then validate links. Supports --dry-run.",
	handoff: "Validate session-handoff.md required V1 sections.",
	doctor: "Run Amber guardrail checks and target classification.",
	plan: [
			"Create a feature-linked vertical-slice plan from a registered feature.",
			"",
			"Required options:",
			"  --target <dir>       Path to the target repository.",
			"  --feature <id>       Feature id (e.g. F001) — must already exist in feature_list.json.",
			"  --title <text>       Short human-readable title for the plan.",
			"",
			"Optional:",
			"  --dry-run            Preview without writing files.",
			"",
			"Examples:",
			"  amber plan --target . --feature F001 --title \"Small slice\"",
			"  amber plan --target . --feature F002 --title \"AccountChargeDrawer dual-step\" --dry-run",
		],
	gate: [
			"Validate that a plan is tied to feature state and has user confirmation, or confirm it.",
			"",
			"Options:",
			"  --plan <path>       Relative path to the plan to gate-check or confirm.",
			"  --confirm           Set the plan's User Confirmation field to confirmed.",
			"",
			"Examples:",
			"  amber gate --target . --plan docs/plans/F001-small-slice.md",
			"  amber gate --target . --plan docs/plans/F001-small-slice.md --confirm",
		],
	review: "Review a plan against static Amber standards and release-readiness checks.",
	accept: [
		"Accept a reviewed plan and append an Amber evolution record.",
		"",
		"Options:",
		"  --plan <path>       Relative path to the plan to accept.",
		"  --session <id>      Optional session id; prints completion-check status as a warning.",
		"  --strict             When used with --session, turn missing completion-check evidence into errors.",
		"",
		"Example:",
		"  amber accept --target path/to/repo --plan docs/plans/F001-small-slice.md",
		"  amber accept --target path/to/repo --plan docs/plans/F001-small-slice.md --session <session-id>",
	],
	pack: "Inspect or validate declarative workflow packs without executing them.",
	profile: "Inspect declarative project profiles.",
	task: "Prepare isolated task ledger, evidence, replay, and worktree artifacts.",
	result: "Inspect replayable task result artifacts without relying on chat history.",
	agent: "Create and control auditable worker/reviewer dispatch records without executing agent work.",
	team: "Inspect, install, pin, update, and roll back local team distribution metadata.",
	maintenance:
		"Inspect stale docs, wiki lint readiness, upgrade guidance, drift, distill candidates, and reviewable maintenance proposals.",
	adoption: [
		"Generate, list, or index safe adoption report artifacts without modifying target repositories.",
		"",
		"Examples:",
		"  amber adoption report --target path/to/repo --output docs/examples/project-adoption-report.md",
		"  amber adoption bundle --reports-dir docs/examples/adoptions --index docs/examples/adoptions-index.md --output-dir docs/examples/project-adoption-bundle",
		"  amber adoption next-actions --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-next-actions.md",
		"  amber adoption decision-record --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-decision-record.md",
		"  amber adoption apply-plan --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-apply-plan.md --dry-run",
		"  amber adoption selected-files --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-selected-files.md --include AGENTS.md",
	],
	loop: [
		"Inspect loop contracts, write dry-run ledger previews, and record manual loop evidence without live scheduling.",
		"",
		"Examples:",
		"  amber loop inspect --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --json",
		"  amber loop run --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --dry-run --output .amber/loops/daily-amber-triage/ledger-preview.json --json",
		"  amber loop record --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --trigger-source manual --stop-reason reviewer-gate-required --output .amber/loops/daily-amber-triage/manual-ledger.json --json",
		"  amber loop status --ledger .amber/loops/daily-amber-triage/manual-ledger.json --json",
		"  amber loop validate-loop --contract path/to/contract.json --json",
	],
	route: [
		"Inspect, validate, and dry-run delivery routes from routes/*.route.json.",
		"",
		"Subcommands:",
		"  list                 List all routes (id, version, stage count).",
		"  inspect <id>         Print a route's stage tree and full JSON.",
		"  validate <file>      Validate a route file; non-zero exit on invalid.",
		"  test <id> --dry-run  Print the ordered stage sequence and gate points.",
		"",
		"Examples:",
		"  amber route list",
		"  amber route inspect feature-standard",
		"  amber route validate routes/feature-standard.route.json",
		"  amber route test bugfix-quick --dry-run",
	],
	session: [
		"Manage session lifecycle: start, status, list, abort, continue, complete-check, verify, approve.",
		"",
		"Subcommands:",
		'  start --goal "..." [--route <id>] [--budget <n>] [--worktree] [--mode interactive]',
		"      Create a new session, write manifest + timeline, optionally create worktree.",
		"  status [<id>]",
		"      Show status of current session or specified session by ID.",
		"  list",
		"      List all sessions in reverse chronological order.",
		"  abort <id>",
		"      Set session status to aborted, write abort event, cleanup worktree.",
		"  continue [<id>]",
		"      Continue a paused or incomplete session from its current stage.",
		"  complete-check --session <id> [--strict]",
		"      Report whether a session has enough evidence to be treated as complete.",
			"  verify --session <id> [--stage <name>] [--command <cmd>] [--result <text>]",
			"      Record a stage_completed event so complete-check sees verification evidence.",
			"  approve --session <id> [--gate <gate-id>]",
			"      Record a gate_passed event so complete-check sees approval evidence.",
			"",
			"Session completion flow:",
			'  amber session start --goal "..."',
			"  amber session continue",
			"  amber session verify --session <id>",
			"  amber session approve --session <id>",
			"  amber session complete-check --session <id>",
			"",
			"Route auto-matching:",
			"  Goals are matched against route trigger goalPattern regexes:",
			"    bugfix-quick     — ^(fix|resolve|patch|repair)\s+.*(bug|defect|issue|error|crash)",
			"    feature-standard — ^(add|implement|create|build)\s+.*feature",
			"    refactor-safe    — ^(refactor|restructure|clean\s*up|simplify|extract)\b",
			"  Pass --route <id> to bypass auto-matching.",
			"",
			"Two-layer approval gates:",
			"  Plan-level:  amber gate --confirm  → edits User Confirmation in the plan .md file.",
			"  Session-level: amber session approve → records gate_passed in the session timeline.",
			"  Both layers must be satisfied for complete-check --strict to pass.",
		"",
		"Examples:",
		'  amber session start --goal "implement user auth"',
		'  amber session start --goal "fix login bug" --route bugfix-quick --worktree',
		'  amber session start --goal "add feature" --mode interactive',
		"  amber session status",
		"  amber session list",
		"  amber session abort <session-id>",
		"  amber session continue",
		"  amber session complete-check --session <session-id>",
			"  amber session verify --session <session-id>",
			"  amber session approve --session <session-id>",
	],
	migrate: [
		"Migrate session manifests to the current schema version, or migrate",
		"legacy state and wiki naming to the Amber Protocol layout.",
		"",
		"Subcommands:",
		"  state        Copy legacy .harness state into .amber (source kept).",
		"  wiki         Rename docs/wiki/agent/harness.md to amber.md and fix links.",
		"  (none)       Migrate session manifests to the current schema version.",
		"",
		"Options:",
		"  --dry-run    Preview changes without writing files (manifest mode).",
		"",
		"Examples:",
		"  amber migrate --target <path>",
		"  amber migrate state --target <path>",
		"  amber migrate wiki --target <path>",
	],
	execution: [
		"Validate execution boundaries and integration contracts.",
		"",
		"Subcommands:",
		"  validate-integration  Validate integration contract structure and hardstops.",
		"  readiness             Review plan for execution boundary violations.",
		"",
		"Examples:",
		"  amber execution validate-integration --contract path/to/contract.json --json",
		"  amber execution readiness --plan path/to/plan.md --target path/to/repo --json",
	],
	security: [
		"Run security governance checks in report-only mode.",
		"",
		"Subcommands:",
		"  audit [--target <dir>] [--output <file>]  Generate a security audit report without mutating target code.",
		"",
		"Examples:",
		"  amber security audit --target path/to/repo",
		"  amber security audit --target path/to/repo --output docs/security-audit.md",
		],
		feature: [
			"Add, list, remove features in feature_list.json and record verification evidence.",
			"",
			"Subcommands:",
			"  add    --id <id> --title <text> [--priority <n>] [--area <area>]",
			"         Register a new feature in feature_list.json.",
			"  list",
			"         List all registered features with status.",
			"  remove --id <id>",
			"         Remove a feature from feature_list.json.",
			"  verify --feature <id> [--command <cmd>] [--result <text>] [--notes <text>]",
			"         Record verification evidence for a feature.",
			"  evidence --feature <id>",
			"         List all recorded evidence for a feature.",
			"",
			"Examples:",
			"  amber feature add --id F001 --title \"User login\" --priority 1 --area auth",
			"  amber feature list",
			"  amber feature remove --id F001",
			"  amber feature verify --feature F001 --command \"npm test\" --result \"42 passed\"",
			"  amber feature evidence --feature F001",
		],
		clean: [
			"Remove amber-generated files from the target repository (reverse of init).",
			"",
			"Options:",
			"  --dry-run    Preview which files would be removed without deleting them.",
			"",
			"Examples:",
			"  amber clean --target path/to/repo",
			"  amber clean --target path/to/repo --dry-run",
	],
		next: [
			"Infer the repo's position in the Amber lifecycle and print the next command to run (read-only).",
			"",
			"Options:",
			"  --target <dir>     Path to the target repository.",
			"  --feature <id>     Focus a specific feature's lifecycle.",
			"  --session <id>     Focus a specific session's lifecycle.",
			"  --json             Emit the machine-readable envelope.",
			"",
			"With no --feature/--session, next auto-selects a focus and states which it chose.",
			"",
			"Examples:",
			"  amber next --target .",
			"  amber next --target . --feature F001",
			"  amber next --target . --session <session-id> --json",
		],
	explain: [
		"Look up Amber error codes, or regenerate the troubleshooting reference.",
		"",
		"Usage:",
		"  amber explain                 List every error code with its layer.",
		"  amber explain <code>          Show cause + fix for one code (bare suffix ok).",
		"  amber explain --markdown <p>  Write the error-code table to a standalone reference file.",
		"",
		"Examples:",
		"  amber explain",
		"  amber explain AMBER_E_FEATURE_NO_EVIDENCE",
		"  amber explain feature_no_evidence",
		"  amber explain --markdown docs/ERROR_CODES.md",
	],
	hooks: [
		"Manage the opt-in git pre-commit governance guard.",
		"",
		"Subcommands:",
		"  install [--warn-only] [--force]",
		"        Install a .git/hooks/pre-commit guard. --warn-only never blocks; --force overwrites a foreign hook.",
		"  uninstall   Remove the Amber guard (restores any backed-up hook).",
		"  status      Report whether the guard is installed and its mode.",
		"  check [--warn-only]",
		"        Run the governance checks now (this is what the hook invokes).",
		"",
		"The hook only reads governance metadata; it never runs project build/test commands.",
		"Bypass once with: AMBER_SKIP_HOOKS=1 git commit ...",
		"",
		"Examples:",
		"  amber hooks install --target .",
		"  amber hooks status --target .",
		"  amber hooks check --target .",
		"  amber hooks uninstall --target .",
	],
	governance: [
		"Create governance documentation for a target repository.",
		"",
		"Subcommands:",
		"  docs         Generate governance documents (CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md).",
		"  evidence     Export governance evidence from sessions or tasks.",
		"  policy       Show governance policy (defaults and overrides).",
		"  audit        Generate comprehensive audit report with policy, sessions, and executions.",
		"",
		"Examples:",
		"  amber governance docs --target path/to/repo",
		"  amber governance docs --target path/to/repo --json",
		"  amber governance evidence --session <id> --output evidence.md",
		"  amber governance evidence --task <id> --output evidence.md --json",
		"  amber governance policy --target path/to/repo",
		"  amber governance policy --target path/to/repo --json",
		"  amber governance audit --target path/to/repo --output audit.md",
		"  amber governance audit --target path/to/repo --output audit.md --since 2025-01-01",
		"  amber governance audit --target path/to/repo --output audit.md --json",
	],
};

const DEFAULT_SUMMARY = "Run Amber Protocol command.";

function commandSummary(command) {
	const help = COMMAND_HELP[command];
	if (help === undefined) {
		return DEFAULT_SUMMARY;
	}
	return Array.isArray(help) ? help.join("\n") : help;
}

module.exports = { commandSummary, COMMAND_HELP };
