"use strict";

// Per-command help text shown by `node scripts/amber.js <command> --help`.
// Single-line summaries are plain strings; multi-line summaries are arrays
// joined with newlines. Adding a command's help is a one-line data edit here,
// not a new branch in the CLI dispatcher.
const COMMAND_HELP = {
	init: "Create missing Amber starter files without overwriting existing files. Supports --dry-run.",
	audit: "Inspect an existing project without writing files. Supports --summary for bounded text output.",
	wiki: "Create missing Wiki starter files, skip existing files, then validate links. Supports --dry-run.",
	handoff: "Validate session-handoff.md required V1 sections.",
	doctor: "Run Amber guardrail checks and target classification.",
	plan: "Create a feature-linked vertical-slice plan without overwriting existing files. Supports --dry-run.",
	gate: "Validate that a plan is tied to feature state and has user confirmation.",
	review: "Review a plan against static Amber standards and release-readiness checks.",
	accept: [
		"Accept a reviewed plan and append an Amber evolution record.",
		"",
		"Options:",
		"  --plan <path>       Relative path to the plan to accept.",
		"  --session <id>      Optional session id; prints completion-check status as a warning.",
		"  --strict             When used with --session, turn missing completion-check evidence into errors.",
		"",
		"Example:",
		"  node scripts/amber.js accept --target path/to/repo --plan docs/plans/F001-small-slice.md",
		"  node scripts/amber.js accept --target path/to/repo --plan docs/plans/F001-small-slice.md --session <session-id>",
	],
	pack: "Inspect or validate declarative workflow packs without executing them.",
	profile: "Inspect declarative project profiles.",
	task: "Prepare isolated task ledger, evidence, replay, and worktree artifacts.",
	result: "Inspect replayable task result artifacts without relying on chat history.",
	agent: "Create and control auditable worker/reviewer dispatch records without executing agent work.",
	team: "Inspect, install, pin, update, and roll back local team distribution metadata.",
	maintenance:
		"Inspect stale docs, wiki lint readiness, upgrade guidance, drift, distill candidates, and reviewable maintenance proposals.",
	adoption: [
		"Generate, list, or index safe adoption report artifacts without modifying target repositories.",
		"",
		"Examples:",
		"  node scripts/amber.js adoption report --target path/to/repo --output docs/examples/project-adoption-report.md",
		"  node scripts/amber.js adoption bundle --reports-dir docs/examples/adoptions --index docs/examples/adoptions-index.md --output-dir docs/examples/project-adoption-bundle",
		"  node scripts/amber.js adoption next-actions --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-next-actions.md",
		"  node scripts/amber.js adoption decision-record --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-decision-record.md",
		"  node scripts/amber.js adoption apply-plan --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-apply-plan.md --dry-run",
		"  node scripts/amber.js adoption selected-files --bundle-dir docs/examples/project-adoption-bundle --output docs/examples/project-adoption-selected-files.md --include AGENTS.md",
	],
	loop: [
		"Inspect loop contracts, write dry-run ledger previews, and record manual loop evidence without live scheduling.",
		"",
		"Examples:",
		"  node scripts/amber.js loop inspect --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --json",
		"  node scripts/amber.js loop run --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --dry-run --output .amber/loops/daily-amber-triage/ledger-preview.json --json",
		"  node scripts/amber.js loop record --file workflow-packs/safe-amber-bootstrap.pack.json --contract daily-amber-triage --trigger-source manual --stop-reason reviewer-gate-required --output .amber/loops/daily-amber-triage/manual-ledger.json --json",
		"  node scripts/amber.js loop status --ledger .amber/loops/daily-amber-triage/manual-ledger.json --json",
		"  node scripts/amber.js loop validate-loop --contract path/to/contract.json --json",
	],
	route: [
		"Inspect, validate, and dry-run delivery routes from routes/*.route.json.",
		"",
		"Subcommands:",
		"  list                 List all routes (id, version, stage count).",
		"  inspect <id>         Print a route's stage tree and full JSON.",
		"  validate <file>      Validate a route file; non-zero exit on invalid.",
		"  test <id> --dry-run  Print the ordered stage sequence and gate points.",
		"",
		"Examples:",
		"  node scripts/amber.js route list",
		"  node scripts/amber.js route inspect feature-standard",
		"  node scripts/amber.js route validate routes/feature-standard.route.json",
		"  node scripts/amber.js route test bugfix-quick --dry-run",
	],
	session: [
		"Manage session lifecycle: start, status, list, abort, continue, complete-check.",
		"",
		"Subcommands:",
		'  start --goal "..." [--route <id>] [--budget <n>] [--worktree] [--mode interactive]',
		"      Create a new session, write manifest + timeline, optionally create worktree.",
		"  status [<id>]",
		"      Show status of current session or specified session by ID.",
		"  list",
		"      List all sessions in reverse chronological order.",
		"  abort <id>",
		"      Set session status to aborted, write abort event, cleanup worktree.",
		"  continue [<id>]",
		"      Continue a paused or incomplete session from its current stage.",
		"  complete-check --session <id> [--strict]",
		"      Report whether a session has enough evidence to be treated as complete.",
		"",
		"Examples:",
		'  node scripts/amber.js session start --goal "implement user auth"',
		'  node scripts/amber.js session start --goal "fix login bug" --route bugfix-quick --worktree',
		'  node scripts/amber.js session start --goal "add feature" --mode interactive',
		"  node scripts/amber.js session status",
		"  node scripts/amber.js session list",
		"  node scripts/amber.js session abort <session-id>",
		"  node scripts/amber.js session continue",
		"  node scripts/amber.js session complete-check --session <session-id>",
	],
	migrate: [
		"Migrate session manifests to the current schema version, or migrate",
		"legacy state and wiki naming to the Amber Protocol layout.",
		"",
		"Subcommands:",
		"  state        Copy legacy .harness state into .amber (source kept).",
		"  wiki         Rename docs/wiki/agent/harness.md to amber.md and fix links.",
		"  (none)       Migrate session manifests to the current schema version.",
		"",
		"Options:",
		"  --dry-run    Preview changes without writing files (manifest mode).",
		"",
		"Examples:",
		"  node scripts/amber.js migrate --target <path>",
		"  node scripts/amber.js migrate state --target <path>",
		"  node scripts/amber.js migrate wiki --target <path>",
	],
	execution: [
		"Validate execution boundaries and integration contracts.",
		"",
		"Subcommands:",
		"  validate-integration  Validate integration contract structure and hardstops.",
		"  readiness             Review plan for execution boundary violations.",
		"",
		"Examples:",
		"  node scripts/amber.js execution validate-integration --contract path/to/contract.json --json",
		"  node scripts/amber.js execution readiness --plan path/to/plan.md --target path/to/repo --json",
	],
	security: [
		"Run security governance checks in report-only mode.",
		"",
		"Subcommands:",
		"  audit [--target <dir>] [--output <file>]  Generate a security audit report without mutating target code.",
		"",
		"Examples:",
		"  node scripts/amber.js security audit --target path/to/repo",
		"  node scripts/amber.js security audit --target path/to/repo --output docs/security-audit.md",
	],
	governance: [
		"Create governance documentation for a target repository.",
		"",
		"Subcommands:",
		"  docs         Generate governance documents (CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md).",
		"  evidence     Export governance evidence from sessions or tasks.",
		"  policy       Show governance policy (defaults and overrides).",
		"  audit        Generate comprehensive audit report with policy, sessions, and executions.",
		"",
		"Examples:",
		"  node scripts/amber.js governance docs --target path/to/repo",
		"  node scripts/amber.js governance docs --target path/to/repo --json",
		"  node scripts/amber.js governance evidence --session <id> --output evidence.md",
		"  node scripts/amber.js governance evidence --task <id> --output evidence.md --json",
		"  node scripts/amber.js governance policy --target path/to/repo",
		"  node scripts/amber.js governance policy --target path/to/repo --json",
		"  node scripts/amber.js governance audit --target path/to/repo --output audit.md",
		"  node scripts/amber.js governance audit --target path/to/repo --output audit.md --since 2025-01-01",
		"  node scripts/amber.js governance audit --target path/to/repo --output audit.md --json",
	],
};

const DEFAULT_SUMMARY = "Run Amber Protocol command.";

function commandSummary(command) {
	const help = COMMAND_HELP[command];
	if (help === undefined) {
		return DEFAULT_SUMMARY;
	}
	return Array.isArray(help) ? help.join("\n") : help;
}

module.exports = { commandSummary, COMMAND_HELP };
