"use strict";

// Facade: the V1–V5.5 mainline lives in scripts/lib/core/ domain modules.
// This file re-exports the public surface so callers keep using
// require("./lib/harness-core") unchanged. Do not add logic here.
const {
	parseArgs,
	printAuditSummary,
	printResult,
} = require("./core/cli-output");
const {
	ADOPTION_DECISION_GATE_IDS,
	ADOPTION_DECISION_STATUSES,
	adoptionDecisionRecordDecisions,
	applyAdoptionDecisionSpecs,
	adoptionDecisionApprovalStatus,
	adoptionDecisionRecordErrorResult,
	buildAdoptionDecisionRecordContent,
	writeAdoptionDecisionRecord,
	adoptionApplyPlanBoundaries,
	adoptionApplyPlanErrorResult,
	buildAdoptionApplyPlanContent,
	writeAdoptionApplyPlan,
	adoptionSelectedFilesBoundaries,
	isSafeSelectableHarnessPath,
	adoptionSelectedFilesErrorResult,
	buildAdoptionSelectedFilesContent,
	writeAdoptionSelectedFiles,
} = require("./core/adoption-proposals");
const {
	adoptionBundleBoundaries,
	buildAdoptionBundleDiffFallbackContent,
	buildAdoptionBundleReadmeContent,
	adoptionBundleErrorResult,
	bundleAdoptionArtifacts,
	extractAdoptionGateFindings,
	extractAdoptionGateMetrics,
	adoptionNextActionsApprovalGates,
	adoptionNextActionsErrorResult,
	buildAdoptionNextActionsContent,
	writeAdoptionNextActions,
} = require("./core/adoption-bundle");
const {
	adoptionGateFindings,
	buildAdoptionGateContent,
	gateAdoptionReport,
	nextAdoptionStatusAction,
	buildAdoptionStatusContent,
	statusAdoptionReports,
} = require("./core/adoption-gate");
const {
	ADOPTION_COMPARE_METRICS,
	buildAdoptionReportContent,
	uniqueAdoptionReportPath,
	parseAdoptionReportMetadata,
	listAdoptionReports,
	buildAdoptionReportsIndexContent,
	writeAdoptionReportsIndex,
	validateAdoptionReports,
	readAdoptionReportMetric,
	parseAdoptionReportForComparison,
	compareStringLists,
	buildMetricComparison,
	buildAdoptionReportDiffContent,
	compareAdoptionReports,
	generateAdoptionReport,
} = require("./core/adoption-reports");
const {
	hasPluginManifestDirectory,
	doctorProductRepo,
	doctor,
} = require("./core/doctor");
const {
	validateProjectProfileData,
	inspectProjectProfile,
} = require("./core/profiles");
const {
	findLoopContract,
	buildLoopLedgerRecord,
	inspectLoopContract,
	dryRunLoopContract,
	recordLoopContract,
	inspectLoopLedger,
} = require("./core/loops");
const {
	validateWorkflowPackData,
	validateLoopContracts,
	describeLoopContracts,
	inspectLoopReadiness,
	validateWorkflowPackReferences,
	inspectWorkflowPack,
	inspectWorkflowPackReadiness,
} = require("./core/workflow-packs");
const {
	listWikiMarkdownFiles,
	detectStaleDocs,
	buildWikiLintCi,
	detectRulePackDrift,
	buildUpgradeAssistant,
	buildMigrationAssistant,
	extractEvolutionFindings,
	readRegressionProposal,
	extractRegressionProposals,
	inspectMaintenance,
	buildMaintenanceProposalContent,
	proposeMaintenance,
} = require("./core/maintenance");
const {
	resolveRegistryPath,
	validateTeamRegistryData,
	loadTeamRegistry,
	compareSemver,
	latestTeamVersion,
	findTeamVersion,
	teamStatePaths,
	summarizeTeamRegistry,
	buildCompatibilityMatrix,
	buildTeamLock,
	writeTeamSnapshot,
	loadTeamLock,
	inspectTeamDistribution,
	installTeamDistribution,
	diffArtifactLists,
	buildTeamUpdatePreview,
	updateTeamDistribution,
	pinTeamDistribution,
	rollbackTeamDistribution,
} = require("./core/team");
const {
	dispatchAgentTask,
	setAgentDispatchStatus,
	recordAgentReview,
} = require("./core/agent-orchestration");
const {
	prepareTaskExecution,
	inspectTaskResult,
	orchestrationPaths,
} = require("./core/task-execution");
const {
	buildPlanContent,
	scaffoldPlan,
	readPlanField,
	validatePlanGate,
	discoverStandards,
	reviewPlan,
	acceptPlan,
} = require("./core/planning");
const {
	loadManifest,
	requireManifestString,
	validateSkillsPath,
	validateCommonManifest,
	validateCodexManifest,
	validateManifests,
	classifyTarget,
} = require("./core/manifests");
const {
	detectCommands,
	detectToolingEvidence,
	addCandidateCommand,
	detectCandidateCommands,
	isLikelyDocumentation,
	listProjectDocs,
	isWikiLike,
	buildSuggestedPatches,
	buildAuditUnknowns,
	buildNextSafeCommand,
	auditProject,
	fileMentionsWiki,
	hasNextAction,
	hasVerificationCommand,
	validateHandoff,
} = require("./core/audit");
const {
	listTemplateFiles,
	copyTemplateFiles,
	scaffoldHarness,
	scaffoldWiki,
} = require("./core/scaffold");
const {
	loadFeatureList,
	findFeatureById,
	validateFeatureListData,
	validateFeatureListFile,
	validateContinuousImprovementStateFile,
	validateWiki,
} = require("./core/validators");
const {
	slugify,
	formatList,
	formatCommandList,
	timestampForFileName,
	escapeMarkdownTableCell,
	extractMarkdownLinks,
	isInsideDirectory,
	isExternalLink,
	stripAnchorAndQuery,
	getSectionBody,
	hasSectionWithBody,
	extractMarkdownListUnderSubheading,
} = require("./core/text-utils");
const {
	AUDIT_IGNORED_DIRECTORY_NAMES,
	resolveTarget,
	pathExists,
	readText,
	readJson,
	writeJson,
	walkFiles,
	isIgnoredAuditPath,
	walkProjectFiles,
	relativeSlash,
	repoRelativePath,
	fileContains,
} = require("./core/fs-utils");
const {
	REPO_ROOT,
	TEMPLATE_ROOT,
	DEFAULT_TEAM_REGISTRY,
	MINIMUM_HARNESS_FILES,
	OPTIONAL_STARTER_WIKI_FILES,
	REQUIRED_HARNESS_FILES,
	VALID_STATUSES,
	REQUIRED_HANDOFF_SECTIONS,
	WIKI_CONTEXT_STARTER_FILES,
	SEMVER_PATTERN,
} = require("./core/constants");


module.exports = {
	MINIMUM_HARNESS_FILES,
	OPTIONAL_STARTER_WIKI_FILES,
	REQUIRED_HARNESS_FILES,
	REQUIRED_HANDOFF_SECTIONS,
	TEMPLATE_ROOT,
	DEFAULT_TEAM_REGISTRY,
	acceptPlan,
	auditProject,
	bundleAdoptionArtifacts,
	classifyTarget,
	compareAdoptionReports,
	dispatchAgentTask,
	doctor,
	dryRunLoopContract,
	inspectMaintenance,
	inspectLoopContract,
	inspectLoopLedger,
	inspectTeamDistribution,
	inspectProjectProfile,
	inspectWorkflowPack,
	inspectWorkflowPackReadiness,
	inspectTaskResult,
	generateAdoptionReport,
	gateAdoptionReport,
	installTeamDistribution,
	listAdoptionReports,
	listTemplateFiles,
	parseArgs,
	pinTeamDistribution,
	proposeMaintenance,
	printResult,
	prepareTaskExecution,
	recordLoopContract,
	recordAgentReview,
	reviewPlan,
	rollbackTeamDistribution,
	scaffoldPlan,
	scaffoldHarness,
	scaffoldWiki,
	setAgentDispatchStatus,
	statusAdoptionReports,
	updateTeamDistribution,
	validateContinuousImprovementStateFile,
	validateFeatureListData,
	validateFeatureListFile,
	validateHandoff,
	validateAdoptionReports,
	validateManifests,
	validatePlanGate,
	validateProjectProfileData,
	validateWorkflowPackData,
	writeAdoptionReportsIndex,
	writeAdoptionNextActions,
	writeAdoptionDecisionRecord,
	writeAdoptionApplyPlan,
	writeAdoptionSelectedFiles,
	validateWiki,
};
